---
kind: pipeline
name: default
type: kubernetes

steps:
- name: build
  pull: if-not-exists
  image: node:14
  commands:
  - npm --loglevel warn install
  - npm run test
  when:
    branch: [ master, features/* ]
    event: pull_request

- name: build_rotm
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  commands:
  - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
  - docker build -t rotm-$${DRONE_COMMIT_SHA} .
  when:
    branch: [ master, features/* ]
    event: pull_request

- name: image_to_quay
  pull: if-not-exists
  image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind
  environment:
    DOCKER_PASSWORD:
      from_secret: DOCKER_PASSWORD
  commands:
    - n=0; while [ "$n" -lt 60 ] && [ ! docker stats --no-stream ]; do n=$(( n + 1 )); sleep 1; done
    - docker login -u="ukhomeofficedigital+drone" -p=$${DOCKER_PASSWORD} quay.io
    - docker tag rotm-$${DRONE_COMMIT_SHA} quay.io/ukhomeofficedigital/rotm:${DRONE_COMMIT_SHA}
    - docker push quay.io/ukhomeofficedigital/rotm:${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: pull_request

- name: clone_repo_build
  pull: if-not-exists
  image: docker:git
  environment:
    DRONE_GIT_USERNAME:
      from_secret: DRONE_GIT_USERNAME
    DRONE_GIT_TOKEN:
      from_secret: DRONE_GIT_TOKEN
  commands:
    - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOffice/kube-rotm.git
    - cd kube-rotm
    - git tag dev-${DRONE_COMMIT_SHA}
    - git push origin --tags
  when:
    branch: master
    event: pull_request

- name: clone_repo_promote
  pull: if-not-exists
  image: docker:git
  environment:
    DRONE_GIT_USERNAME:
      from_secret: DRONE_GIT_USERNAME
    DRONE_GIT_TOKEN:
      from_secret: DRONE_GIT_TOKEN
  commands:
    - git clone https://$${DRONE_GIT_USERNAME}:$${DRONE_GIT_TOKEN}@github.com/UKHomeOffice/kube-rotm.git
    - cd kube-rotm
    - git tag ${DRONE_DEPLOY_TO}-${DRONE_COMMIT_SHA}
    - git push origin --tags
  when:
    event: promote
    target: [ preprod, prod ]

- name: deploy_to_dev
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - cd kube-rotm
    - bin/deploy.sh
  environment:
    KUBE_SERVER_DEV:
      from_secret: kube_server_dev
    KUBE_TOKEN_DEV:
      from_secret: kube_token_dev
    KUBE_NAMESPACE: rotm-dev
    APP_IMAGE_TAG: ${DRONE_COMMIT_SHA}
  when:
    branch: master
    event: pull_request

- name: deploy_to_preprod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - cd kube-rotm
    - bin/deploy.sh
  environment:
    KUBE_SERVER_DEV:
      from_secret: kube_server_dev
    KUBE_TOKEN_DEV:
      from_secret: kube_token_dev
    KUBE_NAMESPACE: rotm-preprod
    APP_IMAGE_TAG: ${DRONE_COMMIT_SHA}
  when:
    event: promote
    target: preprod

- name: deploy_to_prod
  pull: if-not-exists
  image: quay.io/ukhomeofficedigital/kd:v1.14.0
  commands:
    - cd kube-rotm
    - bin/deploy.sh
  environment:
    KUBE_SERVER_PROD:
      from_secret: kube_server_prod
    KUBE_TOKEN_PROD:
      from_secret: kube_token_prod
    KUBE_NAMESPACE: rotm
    APP_IMAGE_TAG: ${DRONE_COMMIT_SHA}
  when:
    event: promote
    target: prod

services:
  - name: docker
    image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/acp/dind

...
