FROM node:8

WORKDIR /test

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY codecept.conf.js codecept.conf.js
COPY config.js config.js
COPY apps apps/

RUN npm --loglevel warn install

CMD npm run test:acceptance
