FROM node:8

WORKDIR /test

COPY package.json package.json
COPY package-lock.json package-lock.json
COPY codecept.conf.js codecept.conf.js
COPY config.js config.js
COPY apps apps/
COPY test.sh test.sh

RUN npm --loglevel warn install
RUN npm run postinstall

CMD npm run test:acceptance
