---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: ingress-network-policy-external-{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: ingress-network-policy-external-{{ .APP_NAME }}
  {{ end }}
spec:
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      app: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-openresty
      {{ else }}
      app: {{ .APP_NAME }}-openresty
      {{ end }}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-external
      ports:
      - port: 8443
        protocol: TCP
      - port: 8080
        protocol: TCP
      - port: 8082
        protocol: TCP
