---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-vault
spec:
  {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
  replicas: 3
  {{ else }}
  replicas: 1
  {{ end }}
  selector:
    matchLabels:
      name: file-vault
      service: file-vault
  template:
    metadata:
      labels:
        name: file-vault
        service: file-vault
    spec:
      containers:
        - name: file-vault
          image: quay.io/ukhomeofficedigital/file-vault:2936ce44e4ca1ad90b3b0526b9abf73c46000de2
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1024Mi"
              cpu: 200m
          envFrom:
            - configMapRef:
                {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
                name: {{ .APP_NAME }}-configmap-{{ .DRONE_SOURCE_BRANCH }}
                {{ else }}
                name: {{ .APP_NAME }}-configmap
                {{ end }}
          env:
            # because the internal virus scanner has a self signed cert!
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
            - name: FILE_VAULT_URL
            {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
              value: https://fv.prod.{{ .APP_NAME }}.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
              value: https://fv-preprod.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
              value: https://fv-dev.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              value: https://fv-dev.notprod.{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.homeoffice.gov.uk
            {{ end }}
            - name: PORT
              value: "3000"
            - name: CLAMAV_REST_URL
              value: https://clamav.virus-scan.svc.cluster.local/scan
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: secret_access_key
            - name: AWS_KMS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: kms_key_id
            - name: AWS_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: bucket_name
            - name: AWS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: passwordhash
                  key: passwordhash
          securityContext:
            runAsNonRoot: true

        - name: keycloak-proxy
          image: quay.io/ukhomeofficedigital/keycloak-gatekeeper:8.0.2
          resources:
            limits:
              memory: "1024Mi"
              cpu: 200m
          env:
            - name: PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: secret
            - name: PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: keycloak-client
                  key: id
            - name: PROXY_REDIRECTION_URL
            {{ if eq .KUBE_NAMESPACE .PROD_ENV }}
              value: https://fv.prod.{{ .APP_NAME }}.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .STG_ENV }}
              value: https://fv-preprod.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .UAT_ENV }}
              value: https://fv-dev.notprod.{{ .APP_NAME }}.homeoffice.gov.uk
            {{ else if eq .KUBE_NAMESPACE .BRANCH_ENV }}
              value: https://fv-dev.notprod.{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}.homeoffice.gov.uk
            {{ end }}
          args:
            - --listen=:10443
            # the url which is used to retrieve the OpenID configuration
            - --discovery-url=https://sso.digital.homeoffice.gov.uk/auth/realms/rotm
            # the endpoint where requests are proxied to
            - --upstream-url=https://127.0.0.1:10444
            # URls that you wish to protect.
            - --resources=uri=/*
            - --tls-cert=/certs/tls.crt
            - --tls-private-key=/certs/tls.key
          ports:
            - containerPort: 10080
            - containerPort: 10443
          securityContext:
            runAsNonRoot: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /certs
              name: certs
            - mountPath: /etc/ssl/certs
              name: bundle
              readOnly: true

        - name: nginx-proxy
          image: quay.io/ukhomeofficedigital/nginx-proxy-govuk:v3
          resources:
            limits:
              memory: "1024Mi"
              cpu: 200m
          env:
{{ file .FILEVAULT_NGINX_SETTINGS | indent 12 }}
          securityContext:
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
            - name: bundle
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: file-vault-cert
        - name: bundle
          configMap:
            name: bundle
