---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-public
  {{ else }}
  name: {{ .APP_NAME }}-public
  {{ end }}
  labels:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    app: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    app: {{ .APP_NAME }}
    {{ end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    app: ha-{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    app: ha-{{ .APP_NAME }}
    {{ end }}
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: https
      port: 8443
      targetPort: https
