---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV -}}
  name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: {{ .APP_NAME }}
  {{ end }}
  labels:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    app: ha-{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
    {{ else }}
    app: ha-{{ .APP_NAME }}
    {{ end }}
spec:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV -}}
  serviceName: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-public
  {{ else }}
  serviceName: {{ .APP_NAME }}-public
  {{ end }}
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      app: ha-{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      app: ha-{{ .APP_NAME }}
      {{ end }}
  template:
    metadata:
      labels:
        {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
        app: ha-{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
        {{ else }}
        app: ha-{{ .APP_NAME }}
        {{ end }}
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: haproxy
          image: 340268328991.dkr.ecr.eu-west-2.amazonaws.com/sas/hof-docker-haproxy:a836d2bfb4178debf4a2eb3d71c346db37a4c56b
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
            - name: peers
              containerPort: 1024
            - name: stats
              containerPort: 8404
            - name: health
              containerPort: 8405
          readinessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: haproxy-config
              mountPath: /usr/local/etc/haproxy
            - name: ssl
              mountPath: /data/ssl
      volumes:
        - name: haproxy-config
          configMap:
            {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
            name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-config
            {{ else }}
            name: {{ .APP_NAME }}-config
            {{ end }}           
            items:
              - key: haproxy.cfg
                path: haproxy.cfg
        - name: ssl
          emptyDir: {}
