---
apiVersion: v1
kind: Service
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-waf-admin-ui
  {{ else }}
  name: {{ .APP_NAME }}-waf-admin-ui
  {{ end }}
  labels:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    app: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-waf-admin-ui
    {{ else }}
    app: {{ .APP_NAME }}-waf-admin-ui
    {{ end }}
spec:
  type: ClusterIP
  selector:
    {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
    app: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-waf-admin-ui
    {{ else }}
    app: {{ .APP_NAME }}-waf-admin-ui
    {{ end }}
  ports:
    - name: admin
      port: 8080
      targetPort: admin
