apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: openresty-np-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: openresty-np
  {{ end }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
          name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-openresty
          app: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-openresty
          {{ else }}
          name: {{ .APP_NAME }}-openresty
          app: {{ .APP_NAME }}-openresty
          {{ end }}
    ports:
    - port: 8080
      protocol: TCP
    - port: 8443
      protocol: TCP
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      app: ha-{{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      app: ha-{{ .APP_NAME }}
      {{ end }}
