apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: ui-redis-pvc-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: ui-redis-pvc
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
