apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
  name: ui-redis-permit-access-{{ .DRONE_SOURCE_BRANCH }}
  {{ else }}
  name: ui-redis-permit-access
  {{ end }}
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
          name: {{ .APP_NAME }}-{{ .DRONE_SOURCE_BRANCH }}-openresty
          {{ else }}
          name: {{ .APP_NAME }}-openresty
          {{ end }}
    ports:
    - port: 6379
      protocol: TCP
  podSelector:
    matchLabels:
      {{ if eq .KUBE_NAMESPACE .BRANCH_ENV }}
      name: ui-redis-{{ .DRONE_SOURCE_BRANCH }}
      {{ else }}
      name: ui-redis
      {{ end }}
