{{ if ne .KUBE_NAMESPACE .BRANCH_ENV }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ui-redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2
{{ end }}
